//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monte_Carlos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleReservacion
    {
        public int IdDetalleReservacion { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> IdReservacion { get; set; }
        public string Pedido { get; set; }
        public Nullable<int> Cantidad { get; set; }
    }
}
