//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monte_Carlos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedores
    {
        public int IdProveedor { get; set; }
        public string Empresa { get; set; }
        public string NumeroDeTelefono { get; set; }
        public string NombreDeContacto { get; set; }
        public string RTN { get; set; }
        public string Observacion { get; set; }
    }
}
